//
//  ListImagesPresenter.swift
//  FlickerImages
//
//  Created by Arpit Srivastava on 16/07/20.
//  Copyright (c) 2020 Arpit Srivastava. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ListImagesPresentationLogic {
    func presentRefresh(response: ListImages.Refresh.Response)
}

class ListImagesPresenter: ListImagesPresentationLogic {
    weak var viewController: ListImagesDisplayLogic?
    
    func presentRefresh(response: ListImages.Refresh.Response) {
        let viewModel = ListImages.Refresh.ViewModel(photoUrls: response.photoUrls)
        viewController?.displayRefresh(viewModel: viewModel)
    }
}
