//
//  ListImagesRouter.swift
//  FlickerImages
//
//  Created by Arpit Srivastava on 28/01/22.
//  Copyright (c) 2022 Arpit Srivastava. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListImagesRoutingLogic {
    func routeToImageDetails(for index: Int)
}

protocol ListImagesDataPassing {
    var dataStore: ListImagesDataStore? { get }
}

class ListImagesRouter: ListImagesRoutingLogic, ListImagesDataPassing {
    weak var viewController: ListImagesViewController?
    var dataStore: ListImagesDataStore?

    // MARK: - ListImagesRoutingLogic
    func routeToImageDetails(for index: Int) {
        let vc = ImageDetailsViewController()
        vc.router?.dataStore?.photo = dataStore?.photos[index]
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
