//
//  ImageDetailsInteractor.swift
//  FlickerImages
//
//  Created by Arpit Srivastava on 28/01/22.
//  Copyright (c) 2022 Arpit Srivastava. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ImageDetailsBusinessLogic: AnyObject {
    func refresh(request: ImageDetails.Refresh.Request)
}

protocol ImageDetailsDataStore: AnyObject {
    var photo: PhotosList.Photos.Photo? { get set }
}

final class ImageDetailsInteractor: ImageDetailsBusinessLogic, ImageDetailsDataStore {

    var presenter: ImageDetailsPresentationLogic?
    var photo: PhotosList.Photos.Photo?

    func refresh(request: ImageDetails.Refresh.Request) {
        guard let photo = photo else {
            assertionFailure("photo should not be nil")
            return
        }

        let title = photo.title
        let url = URL(string: "https://farm\(photo.farm).staticFlickr.com/\(photo.server)/\(photo.id)_\(photo.secret)_m.jpg")!
        let response = ImageDetails.Refresh.Response(title: title, url: url)
        presenter?.presentRefresh(response: response)
    }
}
