//
//  ImageDetailsModels.swift
//  FlickerImages
//
//  Created by Arpit Srivastava on 28/01/22.
//  Copyright (c) 2022 Arpit Srivastava. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum ImageDetails {
    // MARK: Use cases
    
    enum Refresh {
        struct Request {
        }
        struct Response {
            let title: String
            let url: URL
        }
        struct ViewModel {
            let title: String
            let url: URL
        }
    }
}
