//
//  ImageDetailsPresenter.swift
//  FlickerImages
//
//  Created by Arpit Srivastava on 28/01/22.
//  Copyright (c) 2022 Arpit Srivastava. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ImageDetailsPresentationLogic: AnyObject {
    func presentRefresh(response: ImageDetails.Refresh.Response)
}

final class ImageDetailsPresenter: ImageDetailsPresentationLogic {
    weak var viewController: ImageDetailsDisplayLogic?
    
    func presentRefresh(response: ImageDetails.Refresh.Response) {
        let viewModel = ImageDetails.Refresh.ViewModel(title: response.title, url: response.url)
        viewController?.displayRefresh(viewModel: viewModel)
    }
}
